### ISSUE TITLE
Regarding reprudicing the same result of pathomic fusion 

### ISSUE THREAD

**Issue by omniaalwazzan** [mahmoodlab/PathomicFusion#11]
Thanks for sharing the data and the code 

I am very interested in reproducing the same result for the code of the pathomic fusion.

I do have a question regarding the GCN network. 

When I ran the code for all other models ( WSI and Omics), I did not get errors related to the code, and everything seemed to work very well; however, for the GCN model, I got this error. 

TypeError: __init__() got an unexpected keyword argument 'gnn'

which is in the SAGpooling parameters (self.pool1 = SAGPooling(nhid, ratio=pooling_ratio, gnn=GNN)#, nonlinearity=nonlinearity)) 

Am I missing a library?

Thank you very much for your time and effort to help
Omnia

**Comment by Richarizardd** [comment]
HI @omniaalwazzan - Thank you for your interest in the code. To run the GCN part of your code, you would need PyTorch Geometric (1.3.0).

**Comment by omniaalwazzan** [comment]
Thanks for replying.

I guess this could be my problem as my geometric library is 2.0.3 

Again many thanks,
Omnia.
