### ISSUE TITLE
CPC training

### ISSUE THREAD

**Issue by raminnakhli** [mahmoodlab/PathomicFusion#14]
Hi @Richarizardd 

Thanks for sharing the code of this interesting study. I was wondering how the CPC model is trained (pretrained or online training, data). Also, is there a file in the repository that can be used for training the CPC model?

Thanks,

**Comment by Richarizardd** [comment]
Hi @raminnakhli 

You can train CPC via similar repositories / frameworks such as the one linked [here](https://pytorch-lightning-bolts.readthedocs.io/en/latest/self_supervised_models.html) and [here](https://github.com/Spijkervet/contrastive-predictive-coding).

**Comment by raminnakhli** [comment]
Thanks, @Richarizardd. Is the whole data used for the training of the CPC model, or is it trained with respect to the training data of the cross-validation groups each time?
