### ISSUE TITLE
Can't find some .pt files about graph features

### ISSUE THREAD

**Issue by lschctt** [mahmoodlab/PathomicFusion#15]
Hello,
I think that I have found a problem. When I downloaded data from GoogleDrive and tried to train GCN model, I was reminded that there is no folder named all_st_patches_512_cpc in data/TCGA_GBMLGG.

**Comment by chenhao1208** [comment]
:)Hey man, It seems to be no reply here.

**Comment by nauyan** [comment]
@lschctt @chenhao1208 any update on the missing data?

**Comment by Richarizardd** [comment]
Hi @lschctt @chenhao1208 @nauyan - sorry for the delay in response.

Is the data not in .`/TCGA_GBMLGG/all_st_cpc_img/pt_bi/`?

**Comment by nauyan** [comment]
@Richarizardd the data is in `./TCGA_GBMLGG/all_st_cpc_img`. However, the data is missing in the `./data/TCGA_GBMLGG/all_st_patches_512_cpc `directory.

**Comment by Richarizardd** [comment]
As mentioned in the [README](https://github.com/mahmoodlab/PathomicFusion/tree/master/data/TCGA_GBMLGG), the `all_st_cpc` and `all_st_patches_512_cpc` are the same folders which you should copy-paste. I will clarify this further in the README, so that it will reflect more accurate folder names.
