### ISSUE TITLE
CPC_model checkpoints missing

### ISSUE THREAD

**Issue by nauyan** [mahmoodlab/PathomicFusion#16]
Hello @Richarizardd,

I was going through the notebook [Graph Construction.ipynb](http://34.69.187.70:8888/notebooks/Pathomic/PathomicFusion/CellGraph/Graph%20Construction.ipynb). When I tried to execute it I saw that the checkpoint file of the CPC_model model was missing. I have tried to look into previous issues and looked at the entire repo but was not able to find the checkpoints. Therefore, if you could share or point where the checkpoints are placed then it would be really helpful.

Thanks in advance.

**Comment by shubhaminnani** [comment]
Hi @nauyan 
I can see glioma and kidney cpc checkpoint in below drive location. Are you referring to something else?

https://drive.google.com/drive/folders/1swiMrz84V3iuzk8x99vGIBd5FCVncOlf?usp=sharing
Thanks!

**Comment by nauyan** [comment]
@shubhaminnani thanks found it.
