### ISSUE TITLE
Availability of Dataset

### ISSUE THREAD

**Issue by nauyan** [mahmoodlab/PathomicFusion#2]
I have gone through Pathomic Fusion Paper and the code as well. I wanted to know if you have made the whole dataset public. At the moment I am only able to access the processed data that is in the form of 15 Folds.

**Comment by Richarizardd** [comment]
Apologies for the delayed follow-up, and hope this email still finds you well. 

Please see the updated Google Drive for all processed data + models for GBMLGG and KIRC https://drive.google.com/drive/u/1/folders/1swiMrz84V3iuzk8x99vGIBd5FCVncOlf
