### ISSUE TITLE
Is the molueculare subtype feature included in the Grade classification task?

### ISSUE THREAD

**Issue by omniaalwazzan** [mahmoodlab/PathomicFusion#20]
Hi , Chen.

I have a question about the grade classification task.

According to the grade data.csv file, which includes age, gender, histologic grade, and **subtype data**

I understood that features you used to classify the grade included the subtype, correct?

Accordingly, the features for the grade classification task are: age, gender, **subtype data**, and the label is the histologic grade?

Thanks,
Omnia.

**Comment by Richarizardd** [comment]
Hi @omniaalwazzan - grade (or any clinical metadata) is not used in the downstream tasks.

The clinical metadata is separated from the genomic features.

https://github.com/mahmoodlab/PathomicFusion/blob/44b5513cb90c31337276bba92abe515e21c7f6ca/core/utils_data.py#L46

**Comment by omniaalwazzan** [comment]
Thanks for answering @Richarizardd 

Yes that makes sense!

I was quite confused as I used the exact function you referred (line 49) which joins the grade with genomics data; so I thought you were using them :)


Moreover, the Fig.3(A) shown the grade with the molecular subtype puzzled me a bit as if molecular subtype was accounted as one of the features! 

Thanks,
Omnia.

**Comment by Richarizardd** [comment]
Ah apologies for the confusion @omniaalwazzan. In Figure 3A, it is showing how the risks are distributed across the different histomolecular subtypes, from which you see that IDHwt-astrocytomas are prognosticated with higher risk scores. 

Moreover, we see that the grade also correlates with the subtypes, e.g. - most of the IDHwt-astrocytomas that are predicted high risk are also Grade IV. 

All in all, this plot is to help corroborate that the predicted risk scores corroborate with known biomarkers and current grading paradigms.

**Comment by omniaalwazzan** [comment]
Thanks a lot for this clarification!

My confusion is resolved.
