### ISSUE TITLE
A question about the GCN features in the pathgraphomic mode

### ISSUE THREAD

**Issue by yaozhicc** [mahmoodlab/PathomicFusion#4]
Thanks a lot for such an amazing work! 

I have a question about running the code in pathgraphomic mode using the released TCGA-GBM + TCGA-LGG data. I know that the CNN features are extracted from 512 x 512 image patches (each 1024 x 1024 diagnostic patch is cropped into 9 512 x 512 patches with the stride of 256), then I wonder that whether the paired GCN features from 512 x 512 image patches or the 1024 x 1024 diagnostic patch? 

If they come from the 1024 x 1024 diagnostic patch, does this mean that the 9 512 * 512 patches from the same diagnostic patch share the same GCN features and the mean prediction of the 9 512 * 512 patches (along with the other two views) will be used as the prediction for the 1024 x 1024 diagnostic patch? 

Thank you!

**Comment by Richarizardd** [comment]
Hi @yaozhicc 

You are right. The paired GCN features are from the entire 1024 x 1024 diagnostic patch, so as a result, the 9 512 * 512 patches from the same diagnostic patch share the same GCN features. During training, we set up the data loader s.t. at a time, 1 512 x 512 image patch is paired with the GCN node features. However, for evaluation, we average the mean prediction for all 9 512 * 512 patches.

**Comment by yaozhicc** [comment]
I see. Thanks for your reply @Richarizardd !
