### ISSUE TITLE
KNN for Cell Graph Construction

### ISSUE THREAD

**Issue by sgudaparthi** [mahmoodlab/PathomicFusion#5]
I could not find the part in the code where a cell graph is constructed from the histology image (segmented using cGAN). I have two questions in this regard:
1. Could you point me to the code (maybe line numbers) where edge detection using top-K nearest neighbor is performed?
2. Is cGAN part of this code? If not, where should I store the instance mask in the file system after performing nuclei segmentation?

**Comment by Richarizardd** [comment]
Hi @sgudaparthi, thank you for your interest in our repository.

1. I just added a Jupyter Notebook w/ example data on how graph construction is done.
2. cGAN is not part of the code, but can be found in our other code base at: https://github.com/mahmoodlab/NucleiSegmentation
