### ISSUE TITLE
could not find MaskCNN and resnet_custom

### ISSUE THREAD

**Issue by zyuh** [mahmoodlab/PathomicFusion#7]
Hello!
I could not find the part about "MaskCNN" in the code of "from pixelcnn import MaskCNN"  in /CellGraph/model.py,
also "resnet_custom" of "from resnet_custom import *" in the same py file.
where could I find them?

Thanks you very much!

**Comment by Richarizardd** [comment]
Hi @zyuh - uploading that portion of the code shortly!

**Comment by Richarizardd** [comment]
Hi @zyuh added! Also - check out the pretrained models uploaded in the Google Drive.
